### ISSUE TITLE
Ombi 

### ISSUE THREAD

**Issue by Killianbe** [Archmonger/Blackberry-Themes#19] opened 2019-01-22 21:57 UTC
![image](https://user-images.githubusercontent.com/16178815/51568066-215bba80-1e99-11e9-9621-fa48dc7ccce7.png)
Just see :)

**Comment by Archmonger** [comment] 2019-01-22 23:33
Fixes for all were pushed. Clear cache and let me know if the issue is resolved.

**Comment by Archmonger** [comment] 2019-01-22 23:54
Issue reported as fixed on Discord.

**Closed as completed by Archmonger** 2019-01-22 23:54 UTC
